#!/bin/sh
#
# AUTHOR: summerlimes
#
# DATE: Wed Jan 03, 2018
#
# DESC: Elvi to search Toronto Public Library books
# elvis: tpl		-- Search book 
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Toronto Public Library books
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.torontopubliclibrary.ca/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.torontopubliclibrary.ca/search.jsp?Ntt=${escaped_args}"
fi
